/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-09-04 07:54:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookert;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.catalina.util.Introspection;
import bookert.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style/default.css\">\r\n");
      out.write("<title>BOOKERT</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function login(){\r\n");
      out.write("\tif(document.loginform.id.value==\"\")alert(\"아이디를 입력하세요\");\r\n");
      out.write("\telse if(document.loginform.passwd.value==\"\")alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\telse document.loginform.submit();\r\n");
      out.write("}\r\n");
      out.write("function cart(book_num){\r\n");
      out.write("\tvar id = \"");
session.getAttribute("loginId");
      out.write("\";\r\n");
      out.write("\tif(id!=null){\r\n");
      out.write("\t\twindow.open(\"cartPro.jsp?book_num=\"+book_num, \"cart\",\r\n");
      out.write("\t\t\t\t\"width=200,height=200,top=\"+((screen.height-200)/2)+\",left=\"+((screen.width-200)/2));\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(id);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function cartList(){\r\n");
      out.write("\tlocation.href(\"cartListForm.jsp\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("header\r\n");
      out.write("</header>\r\n");
      out.write("<nav>\r\n");
      out.write("nav\r\n");
      out.write("</nav>\r\n");
      out.write("<article>\r\n");
      out.write("\t<section id=\"sidemenu\">\r\n");
      out.write("\t<div id=\"loginbox\">\r\n");
      out.write("\t");

		if (session.getAttribute("loginId")==null) {
		
      out.write("\r\n");
      out.write("\t\t<form method=\"post\" action=\"loginPro.jsp\" name=\"loginform\">\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>아이디 :</td><td> <input type=\"text\" name=\"id\" size=\"12\" maxlength=\"50\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>비밀번호 :</td><td><input type=\"password\" name=\"passwd\" size=\"13\" maxlength=\"16\"\r\n");
      out.write("\t\t\tonkeydown=\"javascript: if (event.keyCode == 13) {login();}\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><a href=\"#\" onclick=\"javascript:login()\">로그인</a></td>\r\n");
      out.write("\t\t\t<td align=\"center\"><a href=\"memberJoinForm.jsp\">회원가입</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");

		}else{
			String loginId = (String)session.getAttribute("loginId");
		
      out.write("\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(loginId);
      out.write("님 접속중</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t");

			if(loginId.equals("manager")){
		
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"managerForm.jsp\">관리자 페이지로</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
}//end if
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td align=\"center\"><a href=\"cartListForm.jsp\">장바구니</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"logoutPro.jsp\">로그아웃</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
}//end else
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\t<section id=\"mainsection\"> \r\n");
      out.write("\t\t");

	      BookertDBBean bookert = BookertDBBean.getInstance();
	      List<BookinfoBean> booklist = new ArrayList<BookinfoBean>();
	
	      booklist = bookert.bookSearch("", null, null);
	
	      int index = 0;
	      int maxindex = 0;
	      int count = 1;
	
	      if (request.getParameter("index") == null) {
	         index = 0;
	         maxindex = 5;
	      } else {
	         index = Integer.parseInt(request.getParameter("index"));
	         maxindex = Integer.parseInt(request.getParameter("maxindex"));
	      }
	
	      for (int i = index; i <= maxindex; i++) {
	         if(i<booklist.size()){
	        	 int book_num = booklist.get(i).getBook_num();
	   
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<table border=\"1\" width=\"785px\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td rowspan=\"4\" style=\"width: 120px;\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"book_image/");
      out.print(book_num);
      out.write(".jpg\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 120px; height: 170px;\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>제목: ");
      out.print(booklist.get(i).getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td rowspan=\"3\" id=\"order\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"javascript:cart(");
      out.print(book_num);
      out.write(")\">장바구니 담기</a><br><br> \r\n");
      out.write("\t\t\t\t<a href=\"#\" onclick=\"javascript:buy(");
      out.print(book_num);
      out.write(")\">구매하기</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>저자: ");
      out.print(booklist.get(i).getAuthor());
      out.write(" 출판사: ");
      out.print(booklist.get(i).getMaker());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>정가: ");
      out.print(booklist.get(i).getPrice());
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");
}else{
		   break;
	   	 }
	   }//end for
	   
      out.write(" \r\n");
      out.write("\t   <br>\r\n");
      out.write("\t   <div style=\"border: 1px solid red; text-align: center;\">\r\n");
      out.write("\t   ");

	      for (int i = 0; i < booklist.size(); i += 6) {
	   
      out.write(" <a href=\"index.jsp?index=");
      out.print(i);
      out.write("&maxindex=");
      out.print(i + 5);
      out.write('"');
      out.write('>');
      out.print(count);
      out.write("</a>|");

	      count++;
	   	  }
	   
      out.write("\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</article>\r\n");
      out.write("<footer>\r\n");
      out.write("footer\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
