/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-09-01 05:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookert;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class infoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<a href=\"managerForm.jsp\">관리자 화면</a>\r\n");

	if(request.getAttribute("alert")!=null){
		
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\talert(\"양식에 맞게 입력하세요\")\t;\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");

	}
		

      out.write("\r\n");
      out.write("<h2>책 정보 등록</h2>\r\n");
      out.write("<form action=\"infoPro.jsp\" method=\"post\">\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>책 제목</td><td><input type=\"text\" name=\"name\" maxlength=\"50\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>지은이</td><td><input type=\"text\" name=\"author\" maxlength=\"30\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>출판사</td><td><input type=\"text\" name=\"maker\" maxlength=\"30\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>분류 1</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"category1\">\r\n");
      out.write("\t\t\t<option value=\"국내서적\">국내서적</option>\r\n");
      out.write("\t\t\t<option value=\"외국서적\">외국서적</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>분류 2</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<select name=\"category2\">\r\n");
      out.write("\t\t\t<option value=\"컴퓨터/IT\">컴퓨터/IT</option>\r\n");
      out.write("\t\t\t<option value=\"청소년\">청소년</option>\r\n");
      out.write("\t\t\t<option value=\"인문교양\">인문교양</option>\r\n");
      out.write("\t\t\t<option value=\"요리\">요리</option>\r\n");
      out.write("\t\t\t<option value=\"역사와 문화\">역사와 문화</option>\r\n");
      out.write("\t\t\t<option value=\"여행\">여행</option>\r\n");
      out.write("\t\t\t<option value=\"소설\">소설</option>\r\n");
      out.write("\t\t\t<option value=\"만화\">만화</option>\r\n");
      out.write("\t\t\t<option value=\"가정과 생활\">가정과 생활</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>가격</td><td><input type=\"number\" name=\"price\">원</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>발행일</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<input type=\"text\" name=\"year\" maxlength=\"4\" size=\"4\">년\r\n");
      out.write("\t\t<input type=\"text\" name=\"month\" maxlength=\"2\" size=\"2\">월\r\n");
      out.write("\t\t<input type=\"text\" name=\"day\" maxlength=\"2\" size=\"2\">일\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"submit\" value=\"등록\"> \r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("<a href=\"searchForm.jsp?name=\">전체 목록</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
