/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-09-02 02:20:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookert;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberJoinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
 request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style>\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var idOk = false;\r\n");
      out.write("function formCheck(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.joinForm.id.value==\"\")alert(\"아이디를 입력하세요\");\r\n");
      out.write("\telse if(document.joinForm.passwd.value==\"\")alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\telse if(document.joinForm.passwd.value!=document.joinForm.repasswd.value)alert(\"비밀번호가 다릅니다\");\r\n");
      out.write("\telse if(document.joinForm.name.value==\"\")alert(\"이름을 입력하세요\");\r\n");
      out.write("\telse if(document.joinForm.address.value==\"\")alert(\"주소를 입력하세요\");\r\n");
      out.write("\telse if(document.joinForm.hp.value==\"\")alert(\"전화번호 입력하세요\");\r\n");
      out.write("\telse if(!idOk)alert(\"아이디 중복확인을 해주세요\");\r\n");
      out.write("\telse document.joinForm.submit();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function idCheck(){\r\n");
      out.write("\tvar inputid = document.joinForm.id.value;\r\n");
      out.write("\tif(inputid==\"\"){\r\n");
      out.write("\t\talert(\"입력된 아이디가 없습니다\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\twindow.open(\"checkIdPro.jsp?id=\"+inputid,\"중복확인\", \"width=400 height=150\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setIdOk(bool){\r\n");
      out.write("\tidOk = bool;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h2 align=\"center\">회원 가입</h2>\r\n");
      out.write("<form method=\"post\" action=\"memberJoinPro.jsp\" name=\"joinForm\">\r\n");
      out.write("\t<table border=\"1\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 아이디</td><td><input type=\"text\" name=\"id\" maxlength=\"20\" style=\"ime-mode:disabled\"><input type=\"button\" value=\"중복확인\" onclick=\"javascript:idCheck()\">\r\n");
      out.write("\t\t\t<br><font size=\"1\" color=\"#bb22bb\">* 영문자, 숫자, 특수문자 포함 20글자 내외로 작성해주세요</font></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 비밀번호 입력</td><td><input type=\"password\" name=\"passwd\" maxlength=\"15\"><font size=\"1\" color=\"#bb22bb\">영문자, 숫자, 특수문자 포함 15자 내외</font></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 비밀번호 확인</td><td><input type=\"password\" name=\"repasswd\" maxlength=\"15\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 이름</td><td><input type=\"text\" name=\"name\" maxlength=\"10\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 기본배송지(주소)</td><td><input type=\"text\" name=\"address\" maxlength=\"50\" size=\"60\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>* 휴대폰 번호</td><td><input type=\"text\" name=\"hp\" maxlength=\"13\"><font size=\"1\" color=\"#bb22bb\">-표시까지 포함해서 적어주세요</font></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t<input type=\"button\" value=\"회원가입 하기\" onclick=\"javascript:formCheck()\">\r\n");
      out.write("\t<input type=\"reset\" value=\"다시 작성하기\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
