/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-08-29 06:27:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookert;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import bookert.*;

public final class searchPro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"5%\">번호</td>\t\r\n");
      out.write("\t\t<td width=\"30%\">제목</td>\r\n");
      out.write("\t\t<td width=\"8%\">출판사</td>\r\n");
      out.write("\t\t<td width=\"9%\">지은이</td>\r\n");
      out.write("\t\t<td width=\"8%\">분류1</td>\r\n");
      out.write("\t\t<td width=\"8%\">분류2</td>\r\n");
      out.write("\t\t<td width=\"8%\">가격</td>\r\n");
      out.write("\t\t<td width=\"10%\">발행일</td>\r\n");
      out.write("\t\t<td width=\"20%\">등록일</td>\r\n");
      out.write("\t</tr>\r\n");


	if(request.getParameter("name")!=null){
		String keyword = request.getParameter("name");
		BookertDBBean bookert = BookertDBBean.getInstance();
		
		List<BookinfoBean> result = bookert.bookSearch(keyword);
		
		if(result.size()>0){
			
			for(int i=0;i<result.size();i++){
				
				int book_num = result.get(i).getBook_num();
				String name = result.get(i).getName();
				String maker = result.get(i).getMaker();
				String author = result.get(i).getAuthor();
				String category1 = result.get(i).getCategory1();
				String category2 = result.get(i).getCategory2();
				int price = result.get(i).getPrice();
				String publication = result.get(i).getPublication();
				Timestamp reg_date = result.get(i).getReg_date();
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(book_num);
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t<td>");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(maker);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(author);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(category1);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(category2);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(price);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(publication);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(reg_date.toString());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"stockForm.jsp?book_num=");
      out.print(book_num);
      out.write("&name=");
      out.print(name);
      out.write("\">확인</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

			}//end for
		}//end if
		
	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
