/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-09-01 02:34:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bookert;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import bookert.*;

public final class stockListForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>재고 확인</h2>\r\n");

	BookertDBBean bookert = BookertDBBean.getInstance();
	String column = request.getParameter("column"); 
	String sort = request.getParameter("sort");
	
	if(column==null)
		column = "";
	if(sort==null){
			sort = "-1";
	}else{
		sort = -Integer.parseInt(sort)+"";
	}
	
	
	List<BookstockBean> stock = bookert.bookStockList(column,sort);

      out.write("\r\n");
      out.write("<table border=\"1\" width=\"70%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"9%\"><a href=\"stockListForm.jsp?column=book_num&sort=");
      out.print(sort);
      out.write("\">책 번호</a></td>\r\n");
      out.write("\t\t<td><a href=\"stockListForm.jsp?column=name&sort=");
      out.print(sort);
      out.write("\">책 제목</a></td>\r\n");
      out.write("\t\t<td width=\"6%\"><a href=\"stockListForm.jsp?column=ea&sort=");
      out.print(sort);
      out.write("\">수량</a></td>\r\n");
      out.write("\t\t<td><a href=\"stockListForm.jsp?column=stock_date&sort=");
      out.print(sort);
      out.write("\">최근 입고일</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

		for(int i=0;i<stock.size();i++){
			int book_num = stock.get(i).getBook_num();
			String name = stock.get(i).getName();
			int ea = stock.get(i).getEa();
			String stock_date = stock.get(i).getStock_date().toString();
		
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(book_num);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(ea);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(stock_date);
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<a href=\"stockForm.jsp\">돌아가기</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
