/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-08-20 01:25:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jdbc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.tomcat.util.threads.ResizableExecutor;
import java.sql.*;

public final class jdbcForm_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jdbc/selectTestPro.jsp", Long.valueOf(1408497938692L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>insert문</h2>\r\n");
      out.write("\r\n");
      out.write("<form action=\"insertTestPro.jsp\" method=\"post\">\r\n");
      out.write("id<input type=\"text\" name=\"id\" maxlength=\"50\"><br>\r\n");
      out.write("pass<input type=\"password\" name=\"passwd\" maxlength=\"16\"><br>\r\n");
      out.write("name<input type=\"text\" name=\"name\" maxlength=\"10\"><br>\r\n");
      out.write("<input type=\"submit\" value=\"OK\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2><a href=\"selectTestPro.jsp\">select문</a></h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"100\">아이디</td>\r\n");
      out.write("\t\t\t<td width=\"100\">패스워드</td>\r\n");
      out.write("\t\t\t<td width=\"100\">이름</td>\r\n");
      out.write("\t\t\t<td width=\"250\">가입일자</td>\r\n");
      out.write("\t\t</tr>\r\n");

Connection conn = null;
PreparedStatement pstmt = null;
ResultSet rs = null;

try{
	String jdbcUrl = "jdbc:mysql://localhost:3306/test";
	String dbId = "root";
	String dbPass = "jsp804";
	
	Class.forName("com.mysql.jdbc.Driver");
	conn = DriverManager.getConnection(jdbcUrl,dbId,dbPass);
	
	
	String sql = "select * from member order by reg_date desc";
	pstmt = conn.prepareStatement(sql);
	rs = pstmt.executeQuery();
	
	while(rs.next()){
		String id = rs.getString("id");
		String passwd = rs.getString("passwd");
		String name = rs.getString("name");
		Timestamp register = rs.getTimestamp("reg_date");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t<td width=\"100\">");
      out.print(id);
      out.write("</td>\r\n");
      out.write("\t\t\t<td width=\"100\">");
      out.print(passwd);
      out.write("</td>\r\n");
      out.write("\t\t\t<td width=\"100\">");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t<td width=\"250\">");
      out.print(register.toString());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t");

	
	}

	
}catch(Exception e){
	e.printStackTrace();
	
}finally{
	if(rs!=null){
		try{rs.close();}catch(SQLException sqle){}
	}
	if(pstmt!=null){
		try{pstmt.close();}catch(SQLException sqle){}
	}
	if(conn!=null){
		try{conn.close();}catch(SQLException sqle){}
	}
	
}	

      out.write("<br>\r\n");
      out.write("<a href=\"jdbcForm_test.jsp\">MAIN</a>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<h2>update문</h2>\r\n");
      out.write("<form action=\"updateTestPro.jsp\" method=\"post\">\r\n");
      out.write("id<input type=\"text\" name=\"id\" maxlength=\"50\"><br>\r\n");
      out.write("pass<input type=\"password\" name=\"passwd\" maxlength=\"16\"><br>\r\n");
      out.write("chainge name<input type=\"text\" name=\"name\" maxlength=\"10\"><br>\r\n");
      out.write("<input type=\"submit\" value=\"OK\">\r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("<h2>delete문</h2>\r\n");
      out.write("<form action=\"deleteTestPro.jsp\" method=\"post\">\r\n");
      out.write("id<input type=\"text\" name=\"id\" maxlength=\"50\"><br>\r\n");
      out.write("pass<input type=\"password\" name=\"passwd\" maxlength=\"16\"><br>\r\n");
      out.write("<input type=\"submit\" value=\"OK\">\r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
